### PR TITLE
Rebased qgis fixes

### PR DESCRIPTION
**Pull request by luis-pereira**
A rebase of https://github.com/lxqt/qtermwidget/pull/499 PR

### CODE REVIEW

**Comment by yan12125** [comment]
Looks good overall. Just curious - is it possible to get rid of assertWithSideEffect by changing some member functions to `const`?

**Comment by luis-pereira** [comment]
> Looks good overall. Just curious - is it possible to get rid of assertWithSideEffect by changing some member functions to `const`?

Sorry for the long delay.
It's possible and done with commit https://github.com/lxqt/qtermwidget/pull/516/commits/634e66e39666a1e9da715295711cb9ffa5bb58fe.

**Comment by yan12125** [comment]
Thank you! I merge this without squashing as those changes are kind of independent, and thus squashing may make git blame harder.

> Sorry for the long delay.

A few days is short for me :)

**Comment by luis-pereira** [comment]
> Thank you! I merge this without squashing as those changes are kind of independent, and thus squashing may make git blame harder.

It would make history a lot harder to understand.

**Comment by yan12125** [comment]
In my opinion, this is a good trade-off - easier debugging (ex: via `git bisect`) is more important than simpler history.

**Pull request merged**
