### PR TITLE
Don't use automatic string conversions

### PR DESCRIPTION
**Pull request by luis-pereira**
* Disables automatic conversions from 8-bit strings (char *) to unicode
  QStrings.
* Disables automatic conversion from QString to 8-bit strings (char *).
* Disables automatic conversions from QByteArray to const char * or const
  void *.
* Disables automatic conversions from QString (or char *) to QUrl.
* Use QStringBuilder for more efficient string creation.

It make us aware of string and encoding conversions.

### CODE REVIEW

**Comment by yan12125** [comment]
Just tested on macOS High Sierra 10.13.6. This branch builds fine. After fix a PTY issue (https://github.com/yan12125/qtermwidget/tree/use-openpty-on-mac), the example program runs fine.

**Comment by luis-pereira** [comment]
@yan12125 Thanks. Pls make a PR for the Apple fix.
Only the *BSD missing :)

**Comment by luis-pereira** [comment]
The changes are indeed platform independent.  It's possible that I missed some spots. Didn't compile it under *BSD.

**Comment by FlingeR** [comment]
@luis-pereira @yan12125 
Builds OK on OpenBSD.

**Comment by yan12125** [comment]
Thank you @FlingeR for testing! Let's go ahead.

**Pull request merged**
