### PR TITLE
Fix unsage mix of bool and int warning.

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks good catch! But looks like there are still bool to int conversion?

By the way, how did you get the warning?

**Comment by yan12125** [comment]
Maybe visual studio somehow accepts booleans for the bitwise or operator, which is designed for integers. How about switching to more verbose yet simpler codes? (not tested)

```C++
if (newLine[x].rendition & RE_BLINK) {
    _hasBlinker = true;
}
```

By the way, I think visual studio is for Windows applications only? There is no plan to support Windows yet: https://github.com/lxqt/qtermwidget/issues/42.

**Comment by doug1234** [comment]
I like your suggestion and I made the change.

I have been able to build on Visual Studio with only a few features unavailable.  If you are interested, I can send a PR your way when I have time.

**Comment by yan12125** [comment]
Thanks!

> I have been able to build on Visual Studio with only a few features unavailable. If you are interested, I can send a PR your way when I have time.

Trivial fixes like this are welcome. If there are non-trivial changes, please discuss at https://github.com/lxqt/qtermwidget/issues/42 first. I will reopen that issue if needed.

**Pull request merged**
