### PR TITLE
pty fallback term

### PR DESCRIPTION
**Pull request by luis-pereira**
- Prefer ranged for over while
- Add a TERM fallback to the pseudoterminal (PTY)

### CODE REVIEW

**Comment by yan12125** [comment]
Looks like this fixed https://github.com/lxqt/qtermwidget/issues/447 ?

**Comment by luis-pereira** [comment]
Yes, it fixes it as "secondary" effect.
Default TERM from `qterminal` needs to be set in `qtermwidget`. Will check how to do that.

**Comment by yan12125** [comment]
qterminal sets TERM via qputenv. Other applications may do something similar. Looks like this approach overwrites existing environment variables?

**Comment by luis-pereira** [comment]
> qterminal sets TERM via qputenv. Other applications may do something similar. Looks like this approach overwrites existing environment variables?

@yan12125  Is there any downside to  https://github.com/lxqt/qterminal/pull/1058 ?

**Comment by luis-pereira** [comment]
@yan12125 `xterm` is a even more sensible fallback.

**Comment by yan12125** [comment]
> Is there any downside to https://github.com/lxqt/qterminal/pull/1058 ?

For qterminal, I don't think so. There might still be an issue for other applications that embed qterm widget. Could you add some sentences to https://github.com/lxqt/qtermwidget/blob/master/CHANGELOG to clarify that?

By the way, https://github.com/lxqt/qterminal/issues/406 may be fixed as a side effect.

> `xterm` is a even more sensible fallback.

I prefer `xterm-256color`. qtermwidget already supports most of commonly-used features in `xterm-256color`.

**Comment by luis-pereira** [comment]
> For qterminal, I don't think so. There might still be an issue for other applications that embed qterm widget. Could you add some sentences to https://github.com/lxqt/qtermwidget/blob/master/CHANGELOG to clarify that?

Ok. Will do that.
What issue for apps that embed `qtermwidget` ? If they don't set `TERM`,  `qtermwidget` set it to `xterm-256color` as a fallback. A method to explicilty do that can be added. 

> By the way, [lxqt/qterminal#406](https://github.com/lxqt/qterminal/issues/406) may be fixed as a side effect.

Good. I wasn't even aware of https://github.com/lxqt/qterminal/issues/406.
 
> I prefer `xterm-256color`. qtermwidget already supports most of commonly-used features in `xterm-256color`.

Agrreed.

**Comment by yan12125** [comment]
If an application sets `TERM` by qputenv (like the current qterminal), will it be overwritten? If so, a migration hint is good.

**Comment by yan12125** [comment]
Thanks! I use rebase instead of squash as the first commit is a different improvement.

**Pull request merged**
