### PR TITLE
Python bindings

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by yan12125** [comment]
pyqt/test.py was removed due to license issues (#224). Specifically,

> we really don't want a single GPL3 file in

I'm not sure if it's OK to re-add that file.

/cc @agaida

**Comment by luis-pereira** [comment]
Wasn't aware of that.
--
Cumprimentos
Regards

A sexta, 8/03/2019, 11:14, Chih-Hsuan Yen <notifications@github.com>
escreveu:

**Comment by luis-pereira** [comment]
It's most certainly not Ok.
Will remove it and write a new test (possibly)

**Comment by agaida** [comment]
erm - which new file?

**Comment by yan12125** [comment]
> erm - which new file? I'm a bit lost here.

The fie pyqt/test.py, which you removed in a previous PR

https://github.com/lxqt/qtermwidget/pull/224/files#diff-aa05e368b97d12430a98c3886d533143

**Comment by yan12125** [comment]
I added a new commit 3945bc49b109dbeb90d7c06bb6cdc13556c77f74 to this pull request. With this commit, pyqt/test.py works fine with qt5-base 5.12.1-2 and python-pyqt5 5.12-2 on Arch Linux.

**Comment by luis-pereira** [comment]
@yan12125 Nice work.
Tested with my configuration:
- SIP 4.19.7
- PyQt5 5.10.1
- Qt 5.9.5

and it build and runs Ok.
GTM.

**Pull request merged**
