### PR TITLE
pyqt: move to SIP 5.x

### PR DESCRIPTION
**Pull request by yan12125**
SIP 4.x is no longer supported [1].

And drop CMake integration for PyQt bindings - it's too messy for SIP
5.x

[1] https://www.riverbankcomputing.com/software/sip/download

### CODE REVIEW

**Comment by yan12125** [comment]
@tsujan some notes about releases:

* This PR should be merged before the next qtermwidget release. Arch has upgraded PyQt5 to a version incompatible with SIP 4.x. As a result SIP 5.x is necessary to build PyQt bindings.
* The version in `pyqt/pyproject.toml` should be kept in sync with the version in `CMakeLists.txt`

**Comment by tsujan** [comment]
@yan12125, I have no knowledge in this area. Would you please merge it yourself?

> The version in pyqt/pyproject.toml should be kept in sync with the version in CMakeLists.txt

Please make the required changes if they aren't related to `QTERMWIDGET_VERSION_MAJOR`, `QTERMWIDGET_VERSION_MINOR` and `QTERMWIDGET_VERSION_PATCH` — I'll set them when releasing LXQt 1.1.0.

**Comment by tsujan** [comment]
Oh, you mean `version = "1.0.0"` in the new `pyqt/pyproject.toml`. OK, I made a note for myself to not forget it. Thanks!

**Comment by yan12125** [comment]
> I have no knowledge in this area. Would you please merge it yourself?

To be honest, I'm not familiar with PyQt either. I called for testing at https://github.com/lxqt/qtermwidget/issues/364#issuecomment-1059993921. If nobody shows up and tests this, I will just merge it next weekend.

> Oh, you mean `version = "1.0.0"` in the new `pyqt/pyproject.toml`

Yep :)

**Pull request merged**
