### PR TITLE
Continue the work from https://github.com/lxqt/qtermwidget/pull/468

### PR DESCRIPTION
**Pull request by bog-dan-ro**

### CODE REVIEW

**Comment by yan12125** [comment]
As I mentioned in https://github.com/lxqt/qtermwidget/pull/468, let's drop Qt 5 support and keep Qt 6 only. Feel free to ask if there are CI errors for a Qt 6-only build.

**Comment by doug1234** [comment]
This feature would help me out a lot.  Is it possible to help out on this effort?

**Comment by yan12125** [comment]
> This feature would help me out a lot. Is it possible to help out on this effort?

@doug1234 Sorry for the late reply. I plan to clean-up this pull request and drop support for Qt 5 during March. It will be great if you help on that during February or March.

**Comment by doug1234** [comment]
> > This feature would help me out a lot. Is it possible to help out on this effort?
> 
> @doug1234 Sorry for the late reply. I plan to clean-up this pull request and drop support for Qt 5 during March. It will be great if you help on that during February or March.

I am still able to help @yan12125 .  I have a version based on the current master that builds with qt6 (but needs testing).  But I am wondering how you want to proceed.  I would suggest either a whole new MR that targets master or merge this MR as into wip-qt6 and I can make a MR for that branch that removes qt5 compatibility and makes a few tweaks.  What do you think?

**Comment by yan12125** [comment]
Thank you very much for the help!

> a whole new MR that targets master

This is better. Qt 6 support may be merged soon (before the next LXQt version), so a WIP branch is not necessary.

**Comment by yan12125** [comment]
Let's move on in https://github.com/lxqt/qtermwidget/pull/532

**Pull request closed without merging**
