### PR TITLE
kptyprocess: Terminate the shell process

### PR DESCRIPTION
**Pull request by palinek**
..in destructor if the process is still running.

This is a workaround and a proper solution should be made on higher
levels (QTerminal?) -> properly try to close the session and optionally
present information from shell about the state.

closes lxqt/lxqt#1432

### CODE REVIEW

**Comment by jsm222** [comment]
Not using `::kill(pid(),SIGHUP);` instead of `terminate(); `which is equal to `::kill(pid(),SIGTERM)` is giving with four tabs open on FreeBSD:
virtual KPtyProcess::~KPtyProcess() process didn't stop upon terminate(),  QProcess::ProcessState(Running) , will try again and then kill
QProcess: Destroyed while process ("/bin/csh") is still running.
virtual KPtyProcess::~KPtyProcess() process didn't stop upon terminate(),  QProcess::ProcessState(Running) , will try again and then kill
QProcess: Destroyed while process ("/bin/csh") is still running.
virtual KPtyProcess::~KPtyProcess() process didn't stop upon terminate(),  QProcess::ProcessState(Running) , will try again and then kill
QProcess: Destroyed while process ("/bin/csh") is still running.
virtual KPtyProcess::~KPtyProcess() process didn't stop upon terminate(),  QProcess::ProcessState(Running) , will try again and then kill
QProcess: Destroyed while process ("/bin/csh") is still running.

konsole is using SIGHUP as well, and qterminal terminates correctly with that AFAICT (it is the signal send with CTRL+D)

**Comment by palinek** [comment]
> Not using ::kill(pid(),SIGHUP); instead of terminate();which is equal to ::kill(pid(),SIGTERM)

I was aware of this, but wanted to use the "plain" Qt ... and it did work with `bash`...

> konsole is using SIGHUP as well, and qterminal terminates correctly with that AFAICT (it is the signal send with CTRL+D)

And AFAIK the CTRL+D doesn't "generate" SIGHUP, but (termios(3)):
```
       VEOF   (004,  EOT,  Ctrl-D) End-of-file character (EOF).  More precisely: this character causes the pending tty buffer to be sent to the waiting user program without waiting for end-of-line.  If it is the first
              character of the line, the read(2) in the user program returns 0, which signifies end-of-file.  Recognized when ICANON is set, and then not passed as input.
```

Nevertheless... using the SIGHUP seems a "proper" way of shutting down the shell forcibly => PR is updated this way.

Thanks for testing & pointing out the problem.

**Comment by ypnos** [comment]
The distinction between SIGHUP coming from the terminal and Ctrl+D behavior is old and well-known. A terminal is supposed to send SIGHUP.

In `bash`, you can conveniently keep background jobs running by exiting via Ctrl+D which will avoid signal propagation to childs.

**Comment by kghost** [comment]
This is TOTALLY wrong, SIGHUP is not generated by terminal, it is generated by pty.

When you close the master side of a pty, SIGHUP is automatically delivered to all process in the tty session, not only the leader aka shell.

So there is nothing related to CTRL-D, the only thing the terminal need to do is closing the master pty fd.

**Comment by ypnos** [comment]
Thank you for the clarification. SIGHUP is typically issued because the terminal closes the connection. Sorry that I worded that in a confusing way. However you can manually send SIGHUP as well for the same effect.

The mechanics still work as I described with regards to Ctrl+D, however I might have drawn the wrong conclusion.

**Comment by kghost** [comment]
No, you never send SIGHUP manually, plz just close the master side of pty. As I described, SIGHUP is supposed to send to ALL processes in the session, not only the leader. And if you send it manually, the leader may receive multiple SIGHUP, which can lead to unspecified behavior.

**Comment by jsm222** [comment]
I have noticed, that by sending SIGHUP as it is now in 0.9 release, all child processes also dies. E.g if you have started a gui process from qterminal it also dies. So if one can close the pty fd (?) we should just do that. Since I guess most users expect child processes to keep running even after the parent terminal is no longer running.

**Comment by jsm222** [comment]
d->pty->close();
seems to do the job

**Comment by palinek** [comment]
> No, you never send SIGHUP manually, plz just close the master side of pty. 

That's done in #179...but if the shell process is not able to stop by itself, we send SIGHUP as I still think, it's better than directly kill it by SIKILL (which would be sent from the `QProcess` d-tor).

**Comment by kghost** [comment]
Modern shell should be able to clean exit when SIGHUP is received, which is generated by closing pty.

If the shell decide not to exit, the terminal should respect that decision, and the terminal mustn't kill shell process. One may set a custom command as the shell, and the custom command may want to stay running background.

You can try gnome-terminal, configure it to run a custom command `nohup sleep 1000` instead of shell, you can verify that after the terminal is closed, the command is still running in the background.

Once more, you do not need to send SIGHUP, as I already explained many times, it is already automatically generated.

**Comment by palinek** [comment]
@kghost  Can you, please, provide specification which states that terminal emulator should leave the spawned process on it's own?

**Comment by agaida** [comment]
@palinek - beware of entering a minefield :P

**Comment by kghost** [comment]
Unfortunately, there are no group or communities maintaining terminal emulator specification. There are just bunch of VT or VTE implementations.

VT100 or VT220 doesn't have capability to kill spawned program, because they are physically separated.

As far as I tested, gnome-terminal or xterm also doesn't kill spawned program.

And other vty related program, like ssh, screen or tmux, also doesn't kill spawned program when exit.

**Pull request merged**
