### PR TITLE
API documentation and naming convention

### PR DESCRIPTION
**Pull request by willbelr**
Documentation was added according to Qt style. Descriptions were taken from code comments and need completion, altough most function are self explanatory. Some named arguments (mostly boolean) were uniformized for consistency with Qt API.

### CODE REVIEW

**Comment by willbelr** [comment]
Please proceed with the merge

**Comment by yan12125** [comment]
Thanks a lot for this and sorry for late response. Two comments/questions:

* Is the document auto-generated or requires manual updates? If the latter, I'm afraid the document will often be out-dated.
* Newly added contents are quite long. A separate file and a link from README.md is better in my opinion.

**Comment by willbelr** [comment]
You're welcome. It is manually generated, automation would be great, but I'm not sure how the functions could be automatically classified otherwise (public slots, properties, etc.).  I figured it would fit well in README.md as it is basic documentation for the plugin usage, but you may place it elsewhere if you wish. Still, I would really like to see those commits merged as I refer to it often. I've been digging in the source files at first, but that should not be needed obviously.

**Comment by yan12125** [comment]
Thanks! Manual updates are also fine if there is a way to remind contributors about updating it. Maybe [add a pull request template](https://docs.github.com/en/enterprise-server@3.0/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates)

**Comment by willbelr** [comment]
I added the pull request template but it won't build anymore. The last commit did not affect the code, hence, did something change with the testing process?

**Comment by stefonarch** [comment]
I see it details:

```
 [ 90%] Generating sip/sipQTermWidgetpart0.cpp, sip/sipQTermWidgetpart1.cpp, sip/sipQTermWidgetpart2.cpp, sip/sipQTermWidgetpart3.cpp, sip/sipQTermWidgetpart4.cpp, sip/sipQTermWidgetpart5.cpp, sip/sipQTermWidgetpart6.cpp, sip/sipQTermWidgetpart7.cpp

sip: Unable to find file "QtGui/QtGuimod.sip"
make[2]: Leaving directory '/__w/qtermwidget/qtermwidget/build'
```

Locally it builds fine here.

**Comment by willbelr** [comment]
> I see it details:
> 
> ```
>  [ 90%] Generating sip/sipQTermWidgetpart0.cpp, sip/sipQTermWidgetpart1.cpp, sip/sipQTermWidgetpart2.cpp, sip/sipQTermWidgetpart3.cpp, sip/sipQTermWidgetpart4.cpp, sip/sipQTermWidgetpart5.cpp, sip/sipQTermWidgetpart6.cpp, sip/sipQTermWidgetpart7.cpp
> 
> sip: Unable to find file "QtGui/QtGuimod.sip"
> make[2]: Leaving directory '/__w/qtermwidget/qtermwidget/build'
> ```
> 
> Locally it builds fine here.

Anything else I should do ?

**Comment by stefonarch** [comment]
Waiting for @yan12125 the cli master.

**Comment by yan12125** [comment]
Thanks for the notice! I pushed a fix at #460. If you rebase this PR on top of the latest git-master, building should be fine.

Regarding the PR itself - thanks it looks good! Will merge after CI turns green.

**Comment by yan12125** [comment]
Thanks a lot for your efforts and patience!

**Pull request merged**
