### PR TITLE
Support combining characters

### PR DESCRIPTION
**Pull request by tsujan**
I consulted the code of the latest Konsole to add support for combining characters to qtermwidget. It was a step-by-step process of testing and bug fixing. Therefore, all parts of this huge change are required.

Closes https://github.com/lxqt/qterminal/issues/319

NOTE: The patch passed my tests, but *please do not merge the PR unless it's either tested thoroughly or reviewed.*

### CODE REVIEW

**Comment by khumba** [comment]
Hi @tsujan!  Thank you very much for preparing this PR.  I can see a lot of work has gone into it, and I'm happy to test.  I've updated to LXQt 2.1 and am running this branch now.

Base consonant + combining character works for me too, hooray!  Sorry to add another case, but what doesn't work yet is adding multiple combining characters at once, e.g. to specify both vowel and tone on a single consonant for words like:

รุ่น (0x0E23 + 0x0E38 + 0x0E48, 0x0E19)  (vowel below, tone mark above)

ยิ้ม (0x0E22 + 0x0E34 + 0x0E49, 0x0E21)  (vowel above, tone mark above vowel)

The first two code points get rendered as tofu and the third code point gets rendered too far to the right (seemingly by an inconsistent amount, looking at the two tone marks I highlighted yellow in my screenshot below, but maybe that detail is a consequence of the existing issue).

I'm not sure if you want to discuss input now too or not, but I'm using Ibus and to type one of these combining characters, I have to type two combining characters in a row, and only the second gets input.

Again, thanks, and I hope these other cases aren't too hard to handle.

qtermwidget-thai

**Comment by tsujan** [comment]
Glad to know that you can test it so thoroughly; your feedback is really appreciated.

> but what doesn't work yet is adding multiple combining characters at once

You're right, I didn't think of the possibility of more than one combining character, but will look into it. Thanks for providing practical examples!

> … but I'm using Ibus and to type one of these combining characters…

Let's focus on the main issues here. Other problems could be reported separately.

**Comment by tsujan** [comment]
I found the place where the issue happened and was able to correct it:
multiple
But there's another issue with selecting and copying this kind of combination. Hopefully it could also be fixed easily. Will tell you when I finish it.

**Comment by tsujan** [comment]
@khumba
The selection problem was caused by a silly mistake. I fixed it and rebased. Would you please test again?

**Comment by tsujan** [comment]
BTW, now the code sets no limit for the number of combining characters. An example with three combining characters:
multiple

**Comment by khumba** [comment]
Awesome, rendering looks good to me now, and also for larger pieces of text.  Thank you very much, @tsujan!

**Comment by tsujan** [comment]
Thanks for testing!

If you encounter any problem in character combination with this PR, please tell me.

**Comment by tsujan** [comment]
@khumba's tests were the thoroughest, and I can't find a problem. Merging…

**Pull request merged**
