### PR TITLE
Make lxqt-build-tools optional

### PR DESCRIPTION
**Pull request by bog-dan-ro**
It's useful to build it on platforms such Android

### CODE REVIEW

**Comment by yan12125** [comment]
Is there an issue with lxqt-build-tools on Android?

**Comment by bog-dan-ro** [comment]
Yes, it's not available nor needed 😉.

**Comment by yan12125** [comment]
It's needed for translation files, which are important for user experience. Could you share more about unavailability? Some package managers include it (ex: [termux](https://github.com/termux/termux-packages/tree/master/x11-packages/lxqt-build-tools)), and installing it from sources should be straightforward as well.

**Comment by tsujan** [comment]
My 2 cents: the problem isn't in QTerminal. Either it's a packaging problem or, *if `lxqt-build-tools` really can't be compiled for Android*, an issue in `lxqt-build-tools` or even Qt.

**Comment by bog-dan-ro** [comment]
The idea is to open this project in qtcreator set an android kit and run it. Without lxqt-build-tools you can't do it.
If lxqt-build-tools are not found and if they are really needed, then IMHO, it should use FetchContent_Declare to automatically get it.

Anyway for my project I end up using QtCreator's terminal emulator which I could run it on Android with Qt6 in no time.

**Comment by yan12125** [comment]
There are a few issues/pull requests mentioning Qt creator. I assume using lxqt-build-tools is already possible.

> If lxqt-build-tools are not found and if they are really needed, then IMHO, it should use FetchContent_Declare to automatically get it.

Feel free to update this PR or open another PR to improve the workflow with Qt creator. I don't use Qt creator, so I may not do it by myself in near future.

**Comment by yan12125** [comment]
Let's continue the work in another PR.

**Pull request closed without merging**
