### PR TITLE
Properly implement the "Action after paste" feature and related fixes

### PR DESCRIPTION
**Pull request by yan12125**
Fixes lxqt/qterminal#43
Fixes lxqt/qterminal#741

### CODE REVIEW

**Comment by stefonarch** [comment]
Compiled both branches in both orders, but "move start" doesn't work, typing after paste continues at the end. Maybe I got something wrong.

**Comment by yan12125** [comment]
> "move start" doesn't work, typing after paste continues at the end

Good point. "move to start" (from https://github.com/lxqt/qtermwidget/pull/6) actually means _scrolling to top_. I don't know whoever wants such a feature, but keeping it there is not a big headache. Maybe I should also update texts in this PR.

**Comment by stefonarch** [comment]
Text is misleading, yes. Did not test multiliners.

**Comment by stefonarch** [comment]
I still do  not manage to  find any difference between the 3 settings for action after paste.

**Comment by yan12125** [comment]
If "Scrolling to bottom" (will be updated in https://github.com/lxqt/qterminal/commit/902fea0fef2a9f81844a845d975a96c14bd1c921) is selected, scrolling up the terminal by a few lines and then pasting brings the terminal back to the bottom (last line). "Scrolling to top" does the opposite and "No move" does nothing else other than pasting.

Thinking again - "No move" and "Scrolling to top" are somewhat confusing. Maybe I should remove that option and keep "Scrolling to bottom" as the default behavior. Looking into #6, it seems that option was added to workaround buggy `scrollToEnd()` line introduced in https://github.com/lxqt/qtermwidget/commit/33f68bc0ec53a46a2abf224776ab6992e25288ec rather than someone really wanted such a feature.

**Comment by yan12125** [comment]
I removed the "Motion after paste" option altogether in the latest revision of https://github.com/lxqt/qterminal/pull/771. Codes are kept in qtermwidget in case someone wants it back after the removal.

**Pull request merged**
