### PR TITLE
Pre-release changes

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Comment by stefonarch** [comment]
See this only now, so merging translations can be done the same?

**Comment by tsujan** [comment]
> So merging translations can be done the same?

Yes. Tomorrow I'll start merging the pre-release changes. So, I'd very appreciate it if translations aren't merged during that.

BTW, could you test the pre-release branches? I'm using them and see no problem but a second pair of eyes would be better. I'll completely understand it if you don't have time for it.

**Comment by stefonarch** [comment]
> BTW, could you test the pre-release branches? I'm using them and see no problem but a second pair of eyes would be better.

Will do today  on arch, was on my to do list. I did some but not all.

**Comment by yan12125** [comment]
As noticed by Stef in https://github.com/lxqt/qtermwidget/pull/450, CI now also fails when building PyQt bindings. That seems an issue in the recently released [PyQt 5.15.6](https://www.riverbankcomputing.com/pipermail/pyqt/2021-November/044345.html). A possible fix for qtermwidget is moving to newer SIP as in [this WIP branch](https://github.com/lxqt/qtermwidget/tree/sip5), but I don't have time to finish it soon. I believe PyQt 5.15.5 or older still works with qtermwidget. Not sure if an item about it in release notes is necessary or not.

On the other hand, I will create another PR to use older PyQt or disable building for PyQt for now.

**Comment by tsujan** [comment]
@yan12125
False positives are inevitable and I didn't mean that CI had a problem. You make a PR in a dependency repository *without merging it*; then you make a PR in the target repository. Of course, CI has no way of knowing that.

I mentioned false positives only for PR testers to know that there's really no problem.

**Comment by yan12125** [comment]
Yep, the failure you mentioned last week is a false positive, but now there is a real failure :)

> On the other hand, I will create another PR to use older PyQt or disable building for PyQt for now.

Pushed https://github.com/lxqt/qtermwidget/pull/451

**Comment by tsujan** [comment]
> but now there is a real failure :)

Oh, sorry, I didn't know that. My knowledge of CI is limited to its final results (≃ 0).

**Comment by yan12125** [comment]
No problem ;)

**Pull request merged**
