### PR TITLE
Falcon.colorscheme

### PR DESCRIPTION
**Pull request by es20490446e**
shot

### CODE REVIEW

**Comment by es20490446e** [comment]
Tested with: [colors](https://gitlab.com/es20490446e/colors)

**Review by luis-pereira — COMMENTED** [review]
It works fine for me. And I like it.
@es20490446e Can you pls squash into a single commit ?

**Comment by es20490446e** [comment]
Ready 👍

**Comment by yan12125** [comment]
Thank you, the screenshot looks nice. Is this color scheme designed by you?

**Comment by es20490446e** [comment]
Yess!

**Comment by yan12125** [comment]
Cool, thanks for the contribution!

**Pull request merged**
