### PR TITLE
Pre-release changes

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Comment by francescmm** [comment]
Hi @tsujan, could we merge [this PR](https://github.com/lxqt/qtermwidget/pull/469) for this release?

**Comment by tsujan** [comment]
> could we merge this PR for this release?

@yan12125 decides about qterminal/qtermwidget PRs.

**Comment by yan12125** [comment]
I merged #469. @tsujan, please update the version in https://github.com/lxqt/qtermwidget/blob/master/lib/qtermwidget.json, thanks!

**Comment by tsujan** [comment]
> please update the version in https://github.com/lxqt/qtermwidget/blob/master/lib/qtermwidget.json

Sure. Thanks for the reminder!

**Comment by tsujan** [comment]
Done. `CHANGELOG` is updated too.

Of course, CI will give false positives.

**Comment by yan12125** [comment]
Thanks! How about replacing `DND` with `drag-and-drop` in changelogs?

**Comment by tsujan** [comment]
> How about replacing DND with drag-and-drop in changelogs?

"DND" is a well-known abbreviation; we even have [XDND](https://freedesktop.org/wiki/Specifications/XDND/).

**Comment by yan12125** [comment]
Alright. It took me several seconds to figure out what DND is :D

**Comment by francescmm** [comment]
> Alright. It took me several seconds to figure out what DND is :D

Is "Dungeons & Dragons", right? :rofl:

**Pull request merged**
