### PR TITLE
Add getForegroundProcessId() function to QTermWidget class

### PR DESCRIPTION
**Pull request by marcusbritanicus**
This will allow terminal apps to check if the user has started a process in the shell and alert them.

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks. Could you update https://github.com/lxqt/qtermwidget/blob/master/pyqt/sip/qtermwidget.sip as well?

**Comment by marcusbritanicus** [comment]
@yan12125 thanks for the review. I'll try to update qtermwidget.sip and ping you back here.

**Comment by marcusbritanicus** [comment]
@yan12125 I've updated qtermwidget.sip as well. Do let me know if it's fine.

**Comment by yan12125** [comment]
Sure, that's good. Thanks!

**Pull request merged**
