### PR TITLE
Remove KDE3 color scheme code

### PR DESCRIPTION
**Pull request by luis-pereira**
KDE3 was a long time ago. It makes no sense keeping it around.
Closes https://github.com/lxqt/lxqt/issues/1854.

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks a lot for cleanups! However, some color schemes in https://github.com/lxqt/qtermwidget/tree/master/lib/color-schemes are still in KDE3 `.schema` format. Could you convert them to the new `.colorscheme` format? Also, I suspect there are still `.scheme` files in the wild, it is better to have a note to tell users how to convert them.

**Comment by luis-pereira** [comment]
Rebased and converted the files. Used Konsole files, they already did the job.

**Comment by luis-pereira** [comment]
> Also, I suspect there are still `.scheme` files in the wild, it is better to have a note to tell users how to convert them.

@yan12125 Where should the note be put ?

**Comment by yan12125** [comment]
> Rebased and converted the files. Used Konsole files, they already did the job.

Great, thanks!

> Where should the note be put ?

Maybe in the next release notes? /cc @tsujan

**Comment by tsujan** [comment]
> Maybe in the next release notes? /cc @tsujan

Yes, we can. Please:
 * Tell me exactly what I should add to the release note; and
 * When the most appropriate time for releasing QTerminal 0.16.1 is.

**Comment by yan12125** [comment]
> Tell me exactly what I should add to the release note

Something like this?

Support for old color scheme format (`*.schema`) is removed in favor of the newer format (`*.colorscheme`). All color schemes in this package is converted, but you may need to convert to the new format if you use a custom color scheme.

> When the most appropriate time for releasing QTerminal 0.16.1 is.

This pull request should be merged after 0.16.1 - it is a backward-incompatible change and users may not expect such changes in a 0.0.1 release.

**Comment by tsujan** [comment]
> This pull request should be merged after 0.16.1 - it is a backward-incompatible change and users may not expect such changes in a 0.0.1 release.

OK. I copy-pasted your suggested note for 0.17.0.

I'll release QTerminal 0.16.1 in 2 days, if you have no objection.

BTW, would you take a look at https://github.com/lxqt/lxqt-config/pull/677 too? It's a bad regression that also needs a point release.

**Comment by yan12125** [comment]
> I'll release QTerminal 0.16.1 in 2 days, if you have no objection.

No problem!

**Comment by yan12125** [comment]
Hi @luis-pereira anything left before removing the draft status from this pull request?

**Comment by luis-pereira** [comment]
@yan12125 No. I will just rebase it.

**Comment by luis-pereira** [comment]
@yan12125 Rebased

**Comment by yan12125** [comment]
Thanks!

**Pull request merged**
