### PR TITLE
functional qtermwidget port to qt6

### PR DESCRIPTION
**Pull request by kitsnotes**
i have created these patches to update qtermwidget to compile and function on qt 6.
it requires the qt5compat module for qtextencoding support.  kde & others seem to be currently at no concrete decision on how to handle the loss of qtextcodec & friends in qt6 as my (admitted limited) research has shown.  this is sad as the replacement in qt6 is insanely limited in comparison..

this adds cmake variable -DUSE_QT6 which defaults to off.  

i've been eating my own dog food by using a qt5 build in qterminal and a qt6 build in my own stuff and so far so good.  i haven't seen any regressions in qterminal using my library in-place instead.

thanks,
~cat

### CODE REVIEW

**Comment by tsujan** [comment]
> kde & others seem to be currently at no concrete decision on how to handle the loss of qtextcodec & friends in qt6

`QStringDecoder` should be used instead of `QTextCodec`, and legacy encodings should be forgotten. KDE devs may not want to do the latter.

> it requires the qt5compat module

IMHO, we should avoid `qt5compat` in porting LXQt to Qt6.

**Comment by kitsnotes** [comment]
> IMHO, we should avoid `qt5compat` in porting LXQt to Qt6.

it can be eliminated if QStringDecoder is adopted (with the loss of any codecs beyond utf-8/utf-16/latin1).  i am targeting musl which is all utf-8 period so i am not angered if obscure codec support goes away but others (esp. outside of the US) might have legitimate issue to raise.

**Comment by tsujan** [comment]
>  i am not angered if obscure codec support goes away but others (esp. outside of the US) might have legitimate issue to raise.

That was Qt devs' decision and, IMO, they had a good reason to get rid of legacy encodings: they're simply too old and deprecated. `qt5compat` will disappear sooner or later. So, I think we'd better avoid it now.

As you said, KDE devs aren't ready to let go of them, but I don't think we need them.

**Comment by tsujan** [comment]
Another thing:

Again, IMHO, we won't need to check Qt's version when porting to Qt6. We could just forget about Qt5 and focus on Qt6. Those who need the Qt5 version could find it here: https://github.com/lxqt/qtermwidget/releases

We'll do so for other LXQt components/apps, but if @yan12125 has a different opinion about QTerminal, I'll accept it.

**Comment by yan12125** [comment]
The long term solution is moving away from legacy stuffs for sure, but replacing QTextCodec seems to require non-trvial changes. I prefer to use qt5compat for now and get rid of QTextCodec in a separate PR.

> we won't need to check Qt's version when porting to Qt6. We could just forget about Qt5 and focus on Qt6

Yes, keeping only Qt 6 support is better. I have once wanted to achieve Qt 5 & 6 compatibility, but gave it up in the middle way due to too many `#if` lines. Sorry for not clarifying that when I mentioned my WIP branch.

**Comment by yan12125** [comment]
Please use a separate PR for new APIs. Also, new APIs should be added to https://github.com/lxqt/qtermwidget/blob/master/pyqt/sip/qtermwidget.sip and https://github.com/lxqt/qtermwidget#public-functions as well.

**Comment by yan12125** [comment]
Let's continue the work at https://github.com/lxqt/qtermwidget/pull/515

**Pull request closed without merging**
