### PR TITLE
Implement terminal margins

### PR DESCRIPTION
**Pull request by Admicos**
(My first PR, let me know if I did anything wrong)

Added new methods: 
    - `void QTermWİdget::setMargin(int)`
    - `int QTermWidget::getMargin() const`
    - `void TerminalDisplay::setMargin(int)`
    - `int TerminalDisplay::margin() const`

### CODE REVIEW

**Comment by yan12125** [comment]
With a large margin (e.g., 20), selecting texts with mouse is broken - selected texts do not match cursor positions.

**Comment by Admicos** [comment]
I just tested selection with 20 and 40px margins and didn't see any issues with text selection. Can you post a gif or something like that? I might be missing something.

**Comment by yan12125** [comment]
Tried again with a fixed-width font and it works. Maybe there's a bug in handling of non-fixed-width fonts, which are not fully supported, anyway.

**Comment by yan12125** [comment]
Thanks, merged!

**Pull request merged**
